version: "2"
networks:
  proxy:
    driver: bridge
services:
  backend:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./backend
      dockerfile: Dockerfile
    image: laravel-backend
    container_name: laravel-backend
    environment:
      DEBUG: 'true'
    working_dir: /var/www
    depends_on: 
      - db-bank
    networks:
        - proxy
    volumes:
      - ./backend:/var/www
  web:
    image: nginx:alpine
    container_name: nginx-bank-service
    depends_on:
      - backend
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - backend
    ports:
      - 80:80
    networks:
      - proxy
  db-bank:
    image: mysql
    container_name: db-bank
    command:
      - --default-authentication-plugin=mysql_native_password
      - --sort_buffer_size=1073741824
    restart: always
    volumes:
      - "./docker/tmp/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    networks:
      - proxy

  